-- REGISTRATION PAGE[before login]
CREATE TABLE Registration(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    USERNAME VARCHAR(89),
    EMAIL VARCHAR(255) UNIQUE,
    MOBILE NUMERIC(11),
    IMAGE VARCHAR(400),
    PASSWORD VARCHAR(89),
    STATE VARCHAR(20),
    CITY VARCHAR(30),
    PIN_CODE NUMERIC(7),
    HOUSE_NAME VARCHAR(89),
    AREA_NAME VARCHAR(89)
);

-- RESERVATION 
CREATE TABLE reservation(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    People NUMERIC(3),
    Date TEXT,
    Time TEXT,
    Mobile NUMERIC(10)
);
